#use_frameworks!

platform :ios, '9.0'

target 'LYZ_EasyNavigation_Example' do
  pod 'LYZ_EasyNavigation', :path => '../'
  target 'LYZ_EasyNavigation_Tests' do
    inherit! :search_paths

    
  end
end
